version: "3"
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - .:/app
  backend:
    image: node:alpine
    command: json-server --watch db.json
    ports:
      - "4000:4000"
    volumes:
      - .:/app