name: Build and Push React Frontend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
      tag_version:
        description: 'Custom tag version'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --coverage --watchAll=false

      - name: Run linting
        run: npm run lint || true

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: ${{ github.event.inputs.environment }}
          REACT_APP_API_URL: ${{ secrets.API_URL }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      image: ${{ steps.meta.outputs.primary_tag }}
      all_tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image tags
        id: meta
        run: |
          TAGS=""
          ENVIRONMENT="${{ github.event.inputs.environment }}"
          CUSTOM_TAG="${{ github.event.inputs.tag_version }}"
          
          if [[ "$ENVIRONMENT" == "production" ]]; then
            TAGS="${TAGS}xilo/personal-portfolio-frontend-main:latest,"
          fi
          
          if [[ -n "$CUSTOM_TAG" ]]; then
            TAGS="${TAGS}xilo/personal-portfolio-frontend-main:${CUSTOM_TAG},"
          fi
          
          TAGS=${TAGS%,}
          
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "Generated tags: ${TAGS}"
          
          # Extract primary tag
          PRIMARY_TAG=$(echo $TAGS | cut -d',' -f1)
          echo "primary_tag=${PRIMARY_TAG}" >> $GITHUB_OUTPUT
          echo "Primary tag: ${PRIMARY_TAG}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          build-args: |
            NODE_ENV=${{ github.event.inputs.environment }}
            REACT_APP_API_URL=${{ secrets.API_URL }}

      - name: Output build summary
        run: |
          echo "## Frontend Build Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Environment:** ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "**Custom Tag:** ${{ github.event.inputs.tag_version || 'None' }}" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered by:** @${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

  security-scan:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Scan built image for vulnerabilities
        run: |
          IMAGE="${{ needs.build-and-push.outputs.image }}"
          
          echo "Scanning image: $IMAGE"
          echo "All built tags: ${{ needs.build-and-push.outputs.all_tags }}"
          
          echo "Running Trivy security scan..."
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --format table \
            --exit-code 0 \
            $IMAGE || echo "Trivy scan completed with findings"
          
          echo "Security scan completed for: $IMAGE"
